name: loldle-ci

on:
  push:
    branches: [ "master" ]

env:
    LOG_LEVEL: info
    DATABASE_USERNAME: vapor_username
    DATABASE_PASSWORD: vapor_password
    DATABASE_NAME: vapor_database

jobs:
    linux:
      runs-on: ubuntu-latest
      env:
        DATABASE_HOST: postgres
      services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: vapor_username
            POSTGRES_PASSWORD: vapor_password
            POSTGRES_DB: vapor_database
      container: swift:5.6-focal
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Run tests
          run: swift test

    macOS:
      runs-on: macos-12
      steps:
        - name: Setup Xcode
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: 13.3
        - name: Checkout
          uses: actions/checkout@v3
        - name: Start PostgreSQL server
          run: brew services start postgresql@14; sleep 5 && pg_isready
        - name: Create database
          run: |
            psql --command="CREATE USER vapor_username PASSWORD 'vapor_password'" --command="\du" postgres
            createdb --owner=vapor_username vapor_database          
        - name: Run tests
          run: swift test
